### ISSUE TITLE
鼠标脚本需要更新，和键盘一个问题 没有：了

### ISSUE THREAD

**Issue by Meo9y** [WangYihang/UsbMiceDataHacker#3]

**Comment by WangYihang** [comment]
感谢反馈，请问可以麻烦您提供流量文件吗?

**Comment by Meo9y** [comment]
链接: https://pan.baidu.com/s/1ftt0T-N0g9yyu0AQy6MBfw  密码: seks

**Comment by lightning-zb** [comment]
好像和流量包文件没关系，和wireshark版本有关，v2的tshark执行提取出来 00:ff:03:00，v3的tshark执行出来的00ff0300

**Comment by kisspanda** [comment]
3年了，不更新一下么
tshark提取出来的，已经没有冒号了，看原py里面，还是Bytes = i.split(":")

**Comment by kisspanda** [comment]
> 感谢反馈，请问可以麻烦您提供流量文件吗?

tshark提取出来的，已经没有冒号了，看原py里面，还是Bytes = i.split(":")

**Comment by WangYihang** [comment]
已解决，感谢各位的反馈。

@kisspanda @lightning-zb @Meo9y
